# Generated by Django 5.0.4 on 2024-08-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceprice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='car_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('All_types', 'All_types')], max_length=20, null=True),
        ),
    ]
