# Generated by Django 5.0.4 on 2024-08-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_serviceprice_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprice',
            name='car_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('all_types', 'all_types')], max_length=20, null=True),
        ),
    ]
