# Generated by Django 5.0.4 on 2024-08-22 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_customeruser_gender_workeruser_is_available'),
        ('services', '0002_alter_serviceprice_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cu_address', to='accounts.customeruser')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_status', models.CharField(blank=True, choices=[('in_way', 'in_way'), ('doing', 'doing')], max_length=10, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('time', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('in_progress', 'in_progress'), ('finished', 'finished')], max_length=15, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('car_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carty_order', to='services.serviceprice')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cu_order', to='accounts.customeruser')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serv_order', to='services.services')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wo_order', to='accounts.workeruser')),
            ],
        ),
    ]
