# Generated by Django 5.0.4 on 2024-08-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orders_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(),
        ),
    ]
