# Generated by Django 5.0.4 on 2024-08-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orders_price_alter_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='car_type',
            field=models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('all_types', 'All_types')], max_length=20, null=True),
        ),
    ]
