# Generated by Django 5.0.4 on 2024-07-09 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_workeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False),
        ),
    ]
