# Generated by Django 5.0.4 on 2024-07-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
