# Generated by Django 5.1.1 on 2024-09-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customeruser_gender_workeruser_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
