# Generated by Django 5.1.1 on 2024-09-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_random_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='workeruser',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'female'), ('male', 'male')], max_length=10, null=True),
        ),
    ]
